### PR TITLE
CON-2137:File System Corruption Fix

### PR DESCRIPTION
**Pull request by AnushaY1916**

### CODE REVIEW

**Review by dileepds — COMMENTED** [review]
1. We can have a common method to find the Filesystem type which can be used for Filesystem corruption checking and Filesystem repair.
2. I think the method executeFilesystemRepair can be used in fsck repair with additional code for handling the exit status.

**Comment by AnushaY1916** [comment]
> 1. We can have a common method to find the Filesystem type which can be used for Filesystem corruption checking and Filesystem repair.

These methods are kept separated because we detect the file system corruption first and then try to repair it only if the user has opted to repair it.

**Comment by AnushaY1916** [comment]
> 2\. I think the method executeFilesystemRepair can be used in fsck repair with additional code for handling the exit status.

fsck has many return codes that need to be handled each one differently and it will be confusing to handle all of the file systems together.

**Review by dileepds — APPROVED** [review]
LGTM

**Review by datamattsson — APPROVED** [review]
LGTM

**Pull request merged**
